enum ProjectRoles {
  ADMIN = 'ADMIN',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  PROFESSOR = 'PROFESSOR',
  STAKEHOLDER = 'STAKEHOLDER',
  DEVELOPER = 'DEVELOPER',
  SPONSOR = 'SPONSOR',
}

export { ProjectRoles }
