export const email = {
    HOSTINGER_EMAIL_HOST: process.env.HOSTINGER_EMAIL_HOST,
    HOSTINGER_EMAIL_PORT: process.env.HOSTINGER_EMAIL_PORT,
    HOSTINGER_EMAIL_USER: process.env.HOSTINGER_EMAIL_USER,
    HOSTINGER_EMAIL_PASSWORD: process.env.HOSTINGER_EMAIL_PASSWORD
  }
